### ISSUE TITLE
krakend-jose/validator supports fetching jwt token from designated header other than Authorization and Cookie key

### ISSUE THREAD

**Issue by yolenw** [luraproject/lura#315]
**Is your feature request related to a problem? Please describe.**
below tells validator can accept jwt token from Authorization or a certain key in Cookie.
https://www.krakend.io/docs/authorization/jwt-validation/
any plan to support extracting jwt token from designated header like: x-mycompany-auth or etc?

**Describe the solution you'd like**
krakend-jose/validator supports http header name apart form cookie "cookie_key" when fetching jwt token

**Describe alternatives you've considered**
did not think of any alternatives so far.

**Additional context**

**Comment by kpacha** [comment]
thanks for the great suggestion!

the feature is not supported because, when working on sensible components, we try to follow the specs keeping things as simple as possible.

One way of covering such requirement could be using a custom http handler plugin. https://www.krakend.io/docs/extending/writing-plugins/
