### ISSUE TITLE
Fail to translate client request parameters

### ISSUE THREAD

**Issue by juaihua** [luraproject/lura#456]
hi, brother

when i use a postman and send a form with post Method, i can not get parameter in the backend. so is there any clue to resolve this problem.

for example,  with the post form below, i can not get request parameter: out_trade_no

![WX20210222-223128](https://user-images.githubusercontent.com/34410992/108721831-6a413a00-755d-11eb-9331-390fbc61ecf6.png)

**Comment by alombarte** [comment]
Hi @juaihua , you are providing very little information to help you out. You should share at least the configuration of your endpoint on `krakend.json` and the output of your backend when used directly. The 500 error is because KrakenD cannot return a valid response to the user. It might be because you are not passing the right headers, because the status code is not a 200 or 201, because the response of the backend is not a JSON file, etc.

**Comment by kpacha** [comment]
closing due inactivity
