### ISSUE TITLE
[Q] Kubernetes KrakenD update configs

### ISSUE THREAD

**Issue by CryptoZifter** [luraproject/lura#478]
Was unsure where to post this so stuck it in issues. I did not see anywhere in the documentation where Krakend can do a dynamic update when the configuration has changed. This is within a Kubernetes cluster so when a ConfigMap updates it would be an option for KrakenD to update however that needs to happen. I know other gateways provide this option and or an admin API to trigger the update. Is this an existing option? if not is it on a roadmap? if not then is there a good way to handle this without dropping the pod and reinstantiating it?

Thanks
CZ

**Comment by ardimaul** [comment]
This is very clear right? https://www.krakend.io/blog/reloading-the-krakend-configuration/
You can mount your config as configmap or secrets inside pods, this will affect downtime. Or you can implement workers load balance inside pods, don't forget to separate health check from krakend if you're not implement workers.
I think krakend with different pods is good, because kubernetes load balancer can handle them with zero downtime, no needed complicated configuration again

**Comment by CryptoZifter** [comment]
A better option would be one of the following which is specifically tied to Kubernetes:

https://github.com/stakater/Reloader

and native to Kubernetes

https://github.com/kubernetes/kubernetes/issues/22368

This is just a reference for those that have similar interest over the docker reflex addition

Thanks
CZ
