### ISSUE TITLE
How to generate / view API endpoint documentation in a visual way (as swagger does)?

### ISSUE THREAD

**Issue by crjacinro** [luraproject/lura#489]
**Is your feature request related to a problem? Please describe.**
Not sure but it helps a lot to view all the endpoints and req/res models and headers required (as swagger does) 

**Describe the solution you'd like**
A desired solution would be a tool that generates html file that can view the API endpoints and its request / response format

**Describe alternatives you've considered**
No alternative that I could think of.

**Additional context**
Response models can be provided (via static proxy models) but I am not sure how the request models can be provided to krakend in order to generate the html.

**Comment by crjacinro** [comment]
Hi is there an update to this query? Thank you.

**Comment by kpacha** [comment]
From the top of my head, I see 2 options for the CE:

1- using the [krakend-postman tool](https://github.com/devopsfaith/krakend-postman/tree/master/cmd/krakend-postman) for generating a descriptor of your API and exploring it with postman

2- using the [krakend-config2dot](https://github.com/devopsfaith/krakend-config2dot/tree/master/cmd/krakend-config2dot) and a custom template (https://github.com/devopsfaith/krakend-config2dot/blob/master/dot.go#L26-L62) to generate the HTML instead of generating the dot file

The EE version includes a swagger/openAPI generator.
