### ISSUE TITLE
Mix the ResponseWrapper and ResponseMetadataWrapper

### ISSUE THREAD

**Issue by kpacha** [luraproject/lura#544]
mix the two interfaces into a single one:

```
type ResponseWrapper interface {
	Data() map[string]interface{}
	Io() io.Reader
	IsComplete() bool
	Headers() map[string][]string
	StatusCode() int
}
```

**Comment by krishna-kunderu** [comment]
Is there a way to update statuscode from modifier response plugin to send different success code. Suppose for create requests, the response code need to be sent 201 instead of 200. With the current ModifierRegisterer, the status code cannot be modified. Wish that this can be updated to send custom codes from the modifier plugin based on the business requirement. Currently CanSet on StatusCode is coming as false.
